/* Harvest v2.2 | (c) 2017 Brandon J. C. Fuller, All Rights Reserved | Requires jQuery 3.1.1 (jquery.org), jQuery UI 1.12.1 (jqueryui.com), and Velocity.js 1.3.1 (velocityjs.org) */var dbPath="data/database2.csv",headerRows=2,types="cal fat sat pufa mufa na pot carbs fiber sugar protein vita vitc ca fe vitd vite vitk b1 b2 b3 b6 b9 b12 cu iod mg mn pho se zn omega3 solfib".split(" "),labelunits=" g g g g mg mg g g g g % % % % % % % % % % % % % % % % % % % % mg g".split(" "),labels="Calories;Total Fat;Saturated Fat;Polyunsaturated Fat;Monounsaturated Fat;Sodium;Potassium;Total Carbohydrates;Dietary Fiber;Sugar;Protein;Vitamin A;Vitamin C;Calcium;Iron".split(";"),detailsHtmlVol=
'<input type="text" class="amount" value="1"><select class="units-list"><option value="ml">ml</option><option value="tsp">tsp</option><option value="tbsp">tbsp</option><option value="fl oz">fl oz</option><option value="cup">cup</option><option value="pint">pint</option><option value="quart">quart</option></select>',detailsHtmlWt='<input type="text" class="amount" value="1"><select class="units-list"><option value="g">g</option><option value="oz">oz</option><option value="lb">lb</option></select>';
null===localStorage.getItem("useritemsindex")&&localStorage.setItem("useritemsindex","");var useritemsindex=localStorage.getItem("useritemsindex").split(","),numuseritems=1===useritemsindex.length&&""===useritemsindex[0]?0:useritemsindex.length,db=[];$.get(dbPath,function(f){var g=types.length+4;f=f.split(",").slice(headerRows*g);for(var B=(f.length-1)/g,q=[],x=0,C=0;C<B;C++){for(var q=[],D=0;D<g;D++)q.push(f[x].trim()),x++;db.push(q)}pushUserData(db)});
function pushUserData(f){for(i=0;i<numuseritems;i++)f.push(localStorage.getItem("useritem"+useritemsindex[i]).split(","));harvest(f)}
function harvest(f){function g(a,b){return Math.round(a/b)*b}function B(a){var b=$("#cloner div.entry").clone();b.children("input.item").autocomplete({source:m,autoFocus:!0,delay:0});a?b.appendTo("#entries").velocity("slideDown",{duration:300,complete:function(){$(this).removeClass("clone").children("input.item").focus()}}):b.appendTo("#entries").removeClass("clone").children("input.item").focus()}function q(){0<numuseritems?$("#my-recipe-count").addClass("full"):($("#my-recipe-count").removeClass("full"),
$("#recipe-drawer").slideUp())}function x(b,e){if(""===b)return alert("Please enter a name for your recipe."),!0;if(-1!==b.search(","))return alert("Sorry, but your recipe's name can't include commas."),!0;if(""===e||isNaN(eval(e)))return alert("Please enter a valid amount for your recipe."),!0;for(a=0;a<numuseritems;a++)if((new RegExp("^"+localStorage.getItem("useritem"+useritemsindex[a]).split(",")[0]+"$","i")).test(b))return alert("You already have a saved recipe with that name."),!0}function C(a){return $("#confirm-delete").is(":checked")?
confirm("Are you sure you want to permanently delete "+a+"? You won't be able to undo this."):!0}var D=f.length,P=labels.length,m=[],Q="ml;tsp;tbsp;fl oz;cup;pint;quart".split(";"),R=["g","oz","lb"],N={},J={},E=[],K=0,S=0,T=0,a,e,b,V={ml:{ml:1,tsp:.2028,tbsp:.0676,floz:.0338,cup:.0042,pint:.0021,quart:.0011},tsp:{ml:4.93,tsp:1,tbsp:.3333,floz:.1666,cup:.0208,pint:.0104,quart:.0052},tbsp:{ml:14.79,tsp:3,tbsp:1,floz:.5,cup:.0625,pint:.0312,quart:.0156},floz:{ml:29.57,tsp:6,tbsp:2,floz:1,cup:.125,pint:.0624,
quart:.0312},cup:{ml:236.59,tsp:48,tbsp:16,floz:8,cup:1,pint:.5,quart:.25},pint:{ml:473.18,tsp:96,tbsp:32,floz:16,cup:2,pint:1,quart:.5},quart:{ml:946.35,tsp:192,tbsp:64,floz:32,cup:4,pint:2,quart:1},g:{g:1,oz:.0353,lb:.0022},oz:{g:28.35,oz:1,lb:.0625},lb:{g:453.59,oz:16,lb:1}};for(a=0;a<D;a++)m.push(f[a][0]);$(document).keypress(function(a){13==a.which&&($("#save-name").is(":focus")||$("#save-amount").is(":focus")||$("#save-units").is(":focus")?$("#save").click():"recipe-name"==document.activeElement.className?
document.activeElement.blur():$("#submit").click())});B(!1);$("#add").on("click",function(){B(!0)});$("#entries").on("click","span.remove",function(){$(this).parent().velocity("slideUp",{duration:300,complete:function(){K++;$(this).attr("data-undo-level",K);E.unshift(K);$("#undo").addClass("active")}})});$("#undo").on("click",function(){1==E.length&&$("#undo").removeClass("active");$("#entries").find('[data-undo-level="'+E[0]+'"]').velocity("slideDown",{duration:300,complete:function(){$(this).removeAttr("data-undo-level");
E.shift()}})});$("#entries").on("click","span.info",function(){var a=$(this).parent().children("div.infodata"),b="none"==a.css("display")?"slideDown":"slideUp";a.velocity(b,{duration:800,easing:[.075,.82,.165,1]});$(this).toggleClass("opened")});$(".popup-control.help").click(function(){$("#help").slideToggle("fast")});$("#recipe-banner").click(function(){$("#table").velocity("scroll",{duration:800,easing:"ease-in-out",offset:-40})});$("#entries").on("autocompleteclose",".item",function(){var b=$(this).parent().children("span.details");
for(a=0;a<D;a++)if(f[a][0]==$(this).val()){-1!=$.inArray(f[a][2],Q)?(b.html(detailsHtmlVol),b.children(".units-list").val(f[a][2]).selectmenu()):-1!=$.inArray(f[a][2],R)?(b.html(detailsHtmlWt),b.children(".units-list").val(f[a][2]).selectmenu()):b.html('<input type="text" class="amount" value="1"><span class="units">'+f[a][2]+"</span>");$(this).parent().children("span.info").css("display","inline-block");b="<ul><li>Amounts per "+f[a][1]+" "+f[a][2]+":</li>";for(e=0;e<P;e++)b+="<li>"+labels[e]+" "+
Number(f[a][e+4].replace("%",""))+labelunits[e]+"</li>";$(this).parent().children("div.infodata").html(b+"</ul>");break}}).change();$("#full-details-list").on("mouseover","li",function(){$(this).parent().children("li").eq(0).addClass("highlight");$("#extras .header li").eq($(this).index()).addClass("highlight")});$("#full-details-list").on("mouseout","li",function(){$("#extras li").removeClass("highlight")});$("#diet-picker li").click(function(){var a=$(this).attr("id");$("#diet-picker").attr("class",
a);$("#cr-colchart").attr("class",a)});$("#delta-view-control li").click(function(){var a=$(this).attr("id");$("#delta-view-control").attr("class",a);$("#blocks").attr("class",a)});var L="";$("#save-units").selectmenu();$("#my-recipe-count").html(numuseritems);q();$("#my-recipes").on("click","#my-recipe-count.full",function(){$("#recipe-drawer").toggle()});var F="",M=[],n=new Date;for(a=numuseritems;a--;)M=localStorage.getItem("useritem"+useritemsindex[a]).split(","),n=new Date(Number(useritemsindex[a])),
n=n.getMonth()+1+"/"+n.getDay()+"/"+n.getFullYear(),F+='<li class="useritem" data-useritem-id="'+useritemsindex[a]+'"><input class="recipe-name" type="text" value="'+M[0]+'"><span class="remove-recipe"></span><span class="recipe-date">'+n+"</span></li>";$("#my-recipes-list").html(F);var H="";$("#my-recipes-list").on("focus","input.recipe-name",function(){H=$(this).val()});$("#my-recipes-list").on("change","input.recipe-name",function(){var a=$(this).val();if(x(a,1))$(this).val(H);else{var b=$(this).parent().attr("data-useritem-id"),
c=localStorage.getItem("useritem"+b).split(",");c[0]=a;localStorage.setItem("useritem"+b,c);m[m.indexOf(H)]=a}});$("#save").click(function(){var a=$("#save-name").val(),b=$("#save-amount").val();x(a,b)||(L=a+","+b+","+$("#save-units").val()+",0,"+L,thisDateStamp=(new Date).getTime(),thisDateStamp=Number(thisDateStamp),""===useritemsindex[0]?useritemsindex[0]=thisDateStamp:useritemsindex.push(thisDateStamp),numuseritems=useritemsindex.length,localStorage.setItem("useritem"+thisDateStamp,L),localStorage.setItem("useritemsindex",
useritemsindex),f.push(L.split(",")),m.push(a),D++,n=new Date(thisDateStamp),n=n.getMonth()+1+"/"+n.getDay()+"/"+n.getFullYear(),$("#save-container").hide(),$("#save-after").show(),$("#my-recipe-count").html(numuseritems),$("#my-recipes-list").prepend('<li class="useritem" data-useritem-id="'+thisDateStamp+'"><input class="recipe-name" type="text" value="'+a+'"><span class="remove-recipe"></span><span class="recipe-date">'+n+"</span></li>"),$("#save-name").val(""),document.activeElement.blur(),q())});
$("#my-recipes-list").on("click","span.remove-recipe",function(){C("this recipe")&&$(this).parent().velocity("slideUp",{duration:300,complete:function(){var a=$(this).attr("data-useritem-id"),b=localStorage.getItem("useritem"+a).split(",")[0];useritemsindex.splice(useritemsindex.indexOf(a),1);m.splice(m.indexOf(b),1);localStorage.removeItem("useritem"+a);localStorage.setItem("useritemsindex",useritemsindex);numuseritems=useritemsindex.length;$("#my-recipe-count").html(numuseritems);$(this).remove();
q()}})});$("#delete-all").click(function(){if(C("all recipes")){$("li.useritem").velocity("slideUp",{duration:300,complete:function(){$(this).remove()}});for(a=0;a<numuseritems;a++){var b=localStorage.getItem("useritem"+useritemsindex[a]).split(",")[0];m.splice(m.indexOf(b),1);localStorage.removeItem("useritem"+useritemsindex[a])}localStorage.setItem("useritemsindex","");useritemsindex=[];numuseritems=0;$("#my-recipe-count").html(numuseritems);q()}});$("#submit").click(function(){function n(){p.sat=
c[2]/u*r;p.pufa=c[3]/u*r;p.mufa=c[4]/u*r;p.ofat=(c[1]-c[2]-c[3]-c[4])/u*r;p.na=c[5]/1E3/u*r;p.k=c[6]/1E3/u*r;p.fiber=c[8]/u*r;p.sugar=c[9]/u*r;p.ocarbs=(c[7]-c[8]-c[9])/u*r;p.protein=c[10]/u*r}var t=performance.now();S++;var c=[],m=[],q=0,y=0,x=!1;for(b in types)c.push(0);var d=$("#spectrum").width();if(736>$(window).width())var h=$("#rank-cal").width(),v={container:d,sat:d,mufa:d,pufa:d,ofat:d,na:d,k:d,fiber:d,sugar:d,ocarbs:d,protein:d};else h=.75*$("#rank-cal").width(),v={container:d,sat:$("#spectrum-sat-label").width(),
mufa:$("#spectrum-mufa-label").width(),pufa:$("#spectrum-pufa-label").width(),ofat:$("#spectrum-ofat-label").width(),na:$("#spectrum-na-label").width(),k:$("#spectrum-k-label").width(),fiber:$("#spectrum-fiber-label").width(),sugar:$("#spectrum-sugar-label").width(),ocarbs:$("#spectrum-ocarbs-label").width(),protein:$("#spectrum-protein-label").width()};var C=c.length,B=$("#servings").val(),I=$("#entries div.entry").not("[data-undo-level]").find("input.item"),r=$("#spectrum-wrapper").width(),E=$("#cr-colchart").height(),
k={cal:[],fat:[],carbs:[],protein:[]},l={},G={cal:h,fat:h,carbs:h,protein:h},K={cal:"Calories",fat:"Fat",carbs:"Carbs",protein:"Protein"},O={cal:"",fat:"g",carbs:"g",protein:"g"},F={cal:[],fat:[],carbs:[],protein:[]},d={};I.splice(0,1);I.each(function(){var b=$(this).val(),d=$(this).parent().children("span.details"),h=d.children("select.units-list"),d=d.children("input.amount").val(),l=[];for(a=0;a<D;a++)if(f[a][0]==b){l.push(b);for(e=0;e<C;e++){q=Number(f[a][e+4].replace("%",""));h.length&&(q*=V[h.val().replace(/\s+/g,
"")][f[a][2].replace(/\s+/g,"")]);if(""===d||isNaN(eval(d))){alert("Please enter a valid amount for all ingredients.");x=!0;break}if(""===B||isNaN(eval(B))){alert("Please enter a valid servings amount.");x=!0;break}y=q/f[a][1]*eval(d)/B;c[e]+=y;y=g(y,.5);l.push(y);4==e+4&&k.cal.push([y,b]);5==e+4&&k.fat.push([y,b]);11==e+4&&k.carbs.push([y,b]);14==e+4&&k.protein.push([y,b])}m.push(l);break}});if(!x){var z=m.length;l.cal=g(c[0],.5);l.fat=g(c[1],.5);l.carbs=g(c[7],.5);l.protein=g(c[10],.5);1==S&&(N=
k,J=l,T=z);var w=0,I=0;for(b in k){k[b].sort(function(a,b){return a[0]-b[0]}).reverse();for(a=0;a<T;a++)for(e=0;e<z;e++)k[b][e].push("none",0),N[b][a][1]==k[b][e][1]&&(w=k[b][e][0]-N[b][a][0],k[b][e][3]=Math.abs(w),0<w?k[b][e][2]="positive":0>w&&(k[b][e][2]="negative"));w=l[b]-J[b];I=Math.abs(w);deltaTAmountP=Math.round(I/J[b]*100);deltaTAmountM=Number(Math.round(l[b]/J[b]+"e1")+"e-1");!0!==isFinite(deltaTAmountP)&&(deltaTAmountP="&#8734");!0!==isFinite(deltaTAmountM)&&(deltaTAmountM="&#8734");w=
0<w?"positive":0>w?"negative":"none";0===l[b]&&(G[b]=0);d[b]='<li class="rank-entry total"><div class="hbar-background" style="width: '+h+'px"><span class="hbar"></span></div><span class="hbar-label"><label>'+l[b]+"</label>"+O[b]+'</span><div class="delta '+w+'"><span class="delta-v">'+I+O[b]+'</span><span class="delta-p">'+deltaTAmountP+'%</span><span class="delta-m">'+deltaTAmountM+'x</span></div><span class="name">Total '+K[b]+"</span></li>";F[b].push(G[b]);for(a=0;a<z;a++)d[b]+='<li class="rank-entry"><div class="hbar-background" style="width: '+
h+'px"><span class="hbar"></span></div><span class="hbar-label"><label>'+k[b][a][0]+"</label>"+O[b]+'</span><span class="delta '+k[b][a][2]+'">'+k[b][a][3]+O[b]+'</span><span class="name">'+k[b][a][1]+"</span></li>",F[b].push(k[b][a][0]/l[b]*h)}N=k;J=l;T=z;var u=c[1]+c[5]/1E3+c[6]/1E3+c[7]+c[10],p={};n();h=0;for(b in p)h+=Math.max(0,p[b]-v[b]);r=r-v.container+(r-h);n();c[0]=5>c[0]?0:50>c[0]?g(c[0],5):g(c[0],10);h=9*c[1];h=5>h?0:50>h?g(h,5):g(h,10);for(a=1;5>a;a++)c[a]=.5>c[a]?0:5>c[a]?g(c[a],.5):
g(c[a],1);for(a=5;7>a;a++)c[a]=5>c[a]?0:140>=c[a]?g(c[a],5):g(c[a],10);for(a=7;11>a;a++)c[a]=.5>c[a]?0:1>c[a]?"<1":g(c[a],1);for(a=11;31>a;a++)c[a]=1>c[a]?0:2>c[a]?2:10>c[a]?g(c[a],2):50>c[a]?g(c[a],5):g(c[a],10);c[31]=g(c[31],1);c[32]=g(c[32],.5);var A={},v=c[7],l=c[10];"<1"==v&&(v=0);"<1"==l&&(l=0);G=9*c[1]+4*v+4*l;0===G?A.fat=A.carbs=A.protein=0:(A.fat=Math.round(9*c[1]/G*100),A.carbs=Math.round(4*v/G*100),A.protein=Math.round(4*l/G*100));v=performance.now();console.log(v-t);L=c.toString();t="";
for(a=0;a<z;a++)t+="<span>"+m[a][0]+"</span>";$("#recipe").html(t);$("#glances").removeClass("animated");$("#gl-cal h1").html("<label>"+c[0]+"</label>");$("#gl-satfat h1").html("<label>"+c[2]+"</label><sub>g</sub>");$("#gl-fiber h1").html("<label>"+c[8]+"</label><sub>g</sub>");$("#gl-sugar h1").html("<label>"+c[9]+"</label><sub>g</sub>");$("#gl-protein h1").html("<label>"+c[10]+"</label><sub>g</sub>");for(a=0;a<C;a++)t=$("#"+types[a]),t.text(c[a]+labelunits[a]),20<=c[a]&&14<a&&31>a?t.parent().removeClass("present").addClass("significant"):
0<c[a]&&14<a&&31>a?t.parent().removeClass("significant").addClass("present"):t.parent().removeClass("present significant");$("#fatcal").text(h);for(b in k)$("#rank-"+b).html(d[b]);var H=!1;1<S&&$("#delta-view-control").show();d="";for(a=0;a<z;a++){d+="<ul><li>"+m[a][0]+"</li>";for(e=1;16>e;e++)d+="<li>"+m[a][e]+labelunits[e-1]+"</li>";d+="</ul>"}$("#full-details-list").html(d);d="<p><b>Ingredients:</b> ";for(a=0;a<z;a++)d+=m[a][0],a<z-1&&(d+=", ");d+="</p><p><b>Amount per serving:</b> ";for(a=0;a<
P;a++)d+=labels[a]+" "+c[a]+labelunits[a],a<P-1&&(d+=", ");$("#plaintext-container").html(d+"</p>");$("#save-after").hide();$("#save-container").show();$("#output").addClass("revealed");$("#footer").addClass("revealed");$("#glances-container").velocity("scroll",{duration:500,easing:"ease-in-out",offset:-40});$("#glances").addClass("animated");$("#glances h1 label").each(function(){if("<1"!=$(this).text()){var a=$(this).text();$(this).velocity({tween:0},{duration:1E3,progress:function(b,c,d,e){$(this).text(Math.round(a*
c))},complete:function(){$(this).text(a)}})}});var M=!1,U=!1,d=window.innerHeight,Q=window.innerWidth,R=(d-$("#spectrum-container").height()/2)/1.3,W=(d-$("#cr").height()/2)/2,X=(d-$("#rankings").height()/2)/1.3;$(window).scroll(function(){$(document).scrollTop()>=$("#abovefold").height()+80&&735<Q?$("#recipe-banner").attr("class","visible"):$("#recipe-banner").attr("class","hidden");if($(document).scrollTop()>$("#spectrum-container").offset().top-R&&!1===M){for(b in p)$("#spectrum-"+b).velocity({width:p[b]},
{duration:1500,easing:[.075,.82,.165,1]});M=!0}if($(document).scrollTop()>$("#cr").offset().top-W&&!1===U){for(b in A)$("#cr-"+b+".vbar-label").html("<label>"+A[b]+"</label><sup>%</sup>"),$("#cr-"+b+"-vbar-mask").velocity({height:E-A[b]/100*E},{duration:800,easing:[.075,.82,.165,1]});$("#cr-colchart-labels .vbar-label label").each(function(){var a=$(this).text();$(this).velocity({tween:0},{duration:1E3,progress:function(b,c,d,e){$(this).text(Math.round(a*c))},complete:function(){$(this).text(a)}})});
U=!0}if($(document).scrollTop()>$("#rankings").offset().top-X&&!1===H){for(b in k)for(a=0;a<z+1;a++)$("#rank-"+b).find(".hbar").eq(a).velocity({width:F[b][a]},{duration:1E3,easing:[.075,.82,.165,1]});H=!0}})}})};
